version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: db-mysql-teste
    environment:
      MYSQL_ROOT_PASSWORD: luis1234
      MYSQL_DATABASE: crud
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
volumes:
  mysql_data:

